FROM rabbitmq:3.11-management

# Define environment variables.
ENV USERRABBIT_DOCKER=leon
ENV PWDSRABBIT_DOCKER=dxt
ENV RABBITMQ_PID_FILE /var/lib/rabbitmq/mnesia/rabbitmq

ADD init.sh /init.sh
RUN chmod +x /init.sh

# Define default command
CMD ["/init.sh"]
