version: "3.8"

services:
  # RabbitMQ Node 1 (Primary)
  rabbitmq1:
    image: rabbitmq:3.11-management
    container_name: rabbitmq1
    hostname: rabbitmq1
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
      RABBITMQ_NODE_NAME: rabbit@rabbitmq1
    ports:
      - "15672:15672"  # Management UI
      - "5672:5672"    # AMQP port
    volumes:
      - rabbitmq1_data:/var/lib/rabbitmq
    networks:
      - rabbitmq_cluster

  # RabbitMQ Node 2
  rabbitmq2:
    image: rabbitmq:3.11-management
    container_name: rabbitmq2
    hostname: rabbitmq2
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
      RABBITMQ_NODE_NAME: rabbit@rabbitmq2
    ports:
      - "15673:15672"  # Management UI
      - "5673:5672"    # AMQP port
    volumes:
      - rabbitmq2_data:/var/lib/rabbitmq
    networks:
      - rabbitmq_cluster
    depends_on:
      - rabbitmq1

  # RabbitMQ Node 3
  rabbitmq3:
    image: rabbitmq:3.11-management
    container_name: rabbitmq3
    hostname: rabbitmq3
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
      RABBITMQ_NODE_NAME: rabbit@rabbitmq3
    ports:
      - "15674:15672"  # Management UI
      - "5674:5672"    # AMQP port
    volumes:
      - rabbitmq3_data:/var/lib/rabbitmq
    networks:
      - rabbitmq_cluster
    depends_on:
      - rabbitmq1

  # HAProxy Load Balancer
  haproxy:
    image: haproxy:2.4
    container_name: rabbitmq_haproxy
    ports:
      - "15675:15672"  # Management UI Load Balanced
      - "5675:5672"    # AMQP Load Balanced
      - "8404:8404"    # HAProxy Stats
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - rabbitmq_cluster
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3

volumes:
  rabbitmq1_data:
  rabbitmq2_data:
  rabbitmq3_data:

networks:
  rabbitmq_cluster:
    driver: bridge
